---

- name: create mariadb pki path
  file:
    state: directory
    path: '{{ mariadb_pki_path }}'
    owner: '{{ mariadb_user }}'
    group: '{{ mariadb_user }}'
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: cert_t
    selevel: s0

- name: create mariadb ssl ca private key
  openssl_privatekey:
    path: tmp/mariadb_ssl_ca.key
    type: RSA
    cipher: aes256
    size: 4096
    passphrase: '{{ mariadb_ca_privatekey_passphrase }}'
  # delegate_to: localhost
  delegate_to: "{{ inventory_hostname }}"

- name: create mariadb ssl ca public key
  openssl_publickey:
    path: tmp/mariadb_ssl_ca.pem
    format: PEM
    privatekey_path: tmp/mariadb_ssl_ca.key
    privatekey_passphrase: '{{ mariadb_ca_privatekey_passphrase }}'
  # delegate_to: localhost
  delegate_to: "{{ inventory_hostname }}"

- name: put the mariadb ssl ca public key to the server
  copy:
    remote_src: true
    src: tmp/mariadb_ssl_ca.pem
    dest: '{{ mariadb_pki_path }}/ca.pem'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: cert_t
    selevel: s0

- name: create mariadb ssl private key
  openssl_privatekey:
    path: '{{ mariadb_pki_path }}/server.key'
    type: RSA
    cipher: aes256
    size: 4096
    passphrase: "{{ mariadb_ca_privatekey_passphrase }}"

- name: create mariadb ssl certificate signing request
  openssl_csr:
    path: '{{ mariadb_pki_path }}/server.csr'
    common_name: '{{ ansible_fqdn }}'
    privatekey_path: '{{ mariadb_pki_path }}/server.key'
    privatekey_passphrase: "{{ mariadb_ca_privatekey_passphrase }}"

- name: fetch mariadb ssl certificate signing request
  fetch:
    src: '{{ mariadb_pki_path }}/server.csr'
    dest: 'tmp/mariadb_{{ ansible_fqdn }}.csr'
    flat: yes
  register: mariadb_register_csr

- name: sign mariadb ssl certificate signing request
  openssl_certificate:
    path: '{{ mariadb_pki_path }}/server.csr'
    privatekey_path: 'tmp/mariadb_ssl_ca.key'
    csr_path: '{{ mariadb_pki_path }}/server.csr'
    provider: selfsigned
    privatekey_passphrase: '{{ mariadb_ca_privatekey_passphrase }}'
  delegate_to: "{{ inventory_hostname }}"
  register: mariadb_register_pem
  tags:
    - skip_ansible_lint
  when: mariadb_register_csr.changed

