---

dependencies: []

galaxy_info:
  role_name: 'mariadb'
  author: 'Adfinis SyGroup AG'
  description: 'Install and manage mariadb/mysql server. pyOpenSSL is locally also required.'
  company: 'Adfinis SyGroup AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.3.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - focal
    - name: EL
      versions:
        - 6
        - 7
        - 8
  galaxy_tags:
    - mariadb
    - mysql
    - database
    - sql
