---
- name: "Install apache"
  apt: name="apache2" state=present

- name: Change default apache http port
  lineinfile: 
    dest: "/etc/apache2/ports.conf" 
    regexp: '^\s?Listen 80' 
    line: "Listen {{ ports.http }}"

- name: Change default apache https port
  replace: 
    path: "/etc/apache2/ports.conf" 
    regexp: '^\s?Listen 443' 
    replace: "Listen {{ ports.https }}"

- name: "Remove default apache's vhost"
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: "Enable apache modules"
  command: "a2enmod {{ item }}"
  with_items:
    - alias 
    - proxy 
    - proxy_fcgi


- include_tasks: vhost.yml
  with_items: "{{ vhosts }}"
  loop_control:
    loop_var: vhost
  notify: restart apache
