---

- name: Create directory for vhost
  file:
    name: "{{ item }}"
    state: directory 
    owner: www-data
    mode: 0750
    recurse: true
  with_items:
    - "/var/www/{{ vhost.domain }}"
    - "/var/www/{{ vhost.domain }}/public_html"
    - "/var/www/{{ vhost.domain }}/logs"


- name: Add apache sites configuration files.
  template:
    src: site.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ vhost.domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache


- name: Enable vhost
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ vhost.domain }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ vhost.domain }}.conf"
    state: link
  notify: restart apache
