---
- name: Recruitment task
  hosts: test_host
  gather_facts: true
  become: true
  pre_tasks:
    - name: Create tmp dir
      file: name=tmp state=directory 
    - name: Install basic dependencies
      apt:
        name: ["ca-certificates", "openssl", "python3-mysqldb", "python3-openssl", "net-tools", "dnsutils", "curl"]
        state: present


  roles:
    - role: 'ssh'
      non_standard_port: 22 # change it
      disable_root_ssh: false

      # source https://github.com/robertdebock/ansible-role-dns
    - role: 'robertdebock.dns'
      dns_zones:
        - name: john.doe
          ttl: 604800
          records:
            - name: "nginx"
              value: 127.0.0.1
            - name: "apache"
              value: 127.0.0.1
            - name: dns1
              value: 127.0.0.1
            - name: dns2
              value: 127.0.0.1
          ns:
            - name: dns1.john.doe.
            - name: dns2.john.doe.

      dns_allow_recursion:
        - any
      dns_options_forwarders:
        - 1.1.1.1
        - 8.8.8.8

      # # fork of https://github.com/adfinis-sygroup/ansible-role-mariadb
    - role: adfinis-sygroup.mariadb # innodb is default storage engine
      mariadb_ssl: true
      mariadb_pki_path: /etc/mysql
      mariadb_user: mysql
      mariadb_ca_privatekey_passphrase: 'Zaq12wx'
      mariadb_databases:
        name: wordpress
      mariadb_users:    # IN THE FUTURE PLEASE USE ANSIBLE VAULT
        - name: wordpress
          host: localhost
          password: fixme
          priv: 'wordpress.*:ALL'

    - role: 'php'
      php_version: "7.3"

    - role: 'apache'
      ports:
        http: 40080
        https: 40443
      vhosts:
        - domain: apache.john.doe
          listen_on: 127.0.0.1:40080
        - domain: nginx.john.doe
          listen_on: 127.0.0.1:40080


    - role: 'nginx'
      reverse_proxies:
        - domain: _ # default
          upstream_servers: ['127.0.0.1:40080']
          port: 80
      vhosts: []

    - role: 'wordpress'
      wordpress_path: '/var/www/nginx.john.doe/public_html'
      directory_owner: 'www-data'
      # IN THE FUTURE PLEASE USE ANSIBLE VAULT
      db_name: wordpress
      db_user: wordpress
      db_password: fixme

  ################

  post_tasks:
    - name: Add phpinfo to apache.john.doe vhost
      shell:
        cmd: 'echo "<?php\n phpinfo();" > /var/www/apache.john.doe/public_html/index.php'

    - name: Resolve domains with localhost's server
      shell:
        cmd: 'echo nameserver 127.0.0.1 > /etc/resolv.conf'




