---
- name: Pass recruitment task
  hosts: test_host
  gather_facts: true
  become: true
  pre_tasks:
    - name: Create tmp dir
      file: name=tmp state=directory 
    - name: Install python3-openssl
      apt: name=python3-openssl state=present

  roles:
    - role: 'ssh'
      non_standard_port: 40022
      disable_root_ssh: false

    - role: 'robertdebock.dns'
      dns_zones:
        - name: john.doe
          ttl: 604800
          records:
            - name: "nginx"
              value: 127.0.0.1
            - name: "apache"
              value: 127.0.0.1
            - name: dns1
              value: 127.0.0.1
            - name: dns2
              value: 127.0.0.1
          ns:
            - name: dns1.john.doe.
            - name: dns2.john.doe.

    - role: adfinis-sygroup.mariadb # innodb is default storage engine
      mariadb_ssl: true
      mariadb_pki_path: /etc/mysql
      mariadb_user: mysql
      mariadb_ca_privatekey_passphrase: 'Zaq12wx'
