---

- name: Create directory for vhost
  file:
    name: "{{ item }}"
    state: directory 
    owner: www-data
    mode: 0750
    recurse: true
  with_items:
    - "/var/www/apache.john.doe"
    - "/var/www/apache.john.doe/public_html"
    - "/var/www/apache.john.doe/logs"


- name: Add index.php
  shell:
    cmd: 'echo "<?php\n phpinfo();" > /var/www/apache.john.doe/public_html/index.php'


- name: include apache.john.doe vars
  include_vars: file=apache_john_doe.yml

- name: Add apache sites configuration files.
  template:
    src: site.conf.j2
    dest: "{{ apache_conf_path }}/sites-available/{{ servername }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache


- name: Enable vhost
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ servername }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ servername }}.conf"
    state: link
  notify: restart apache
