
- name: Install php-fpm
  apt:
    name: "php{{ php_version }}-fpm"
    state: present

- name: start service
  service:
    name: "php{{ php_version }}-fpm"
    state: started


- name: listen php-fpm on host
  lineinfile: 
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf" 
    regexp: '^listen' 
    line: 'listen = 127.0.0.1:9000'




