
- name: Install php with php-fpm
  apt:
    name: [ "php{{ php_version }}-fpm", "php{{ php_version }}",  "php7.3-mysql"]
    state: present

- name: start service
  service:
    name: "php{{ php_version }}-fpm"
    state: started


- name: listen php-fpm on host
  lineinfile: 
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf" 
    regexp: '^listen = ' 
    line: 'listen = 127.0.0.1:9000'
  notify: restart php-fpm





